=== giovannitorsello/crmcom2Server/olo2olo/xsd/xml1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.olo.it/Request" targetNamespace="http://www.olo.it/Request" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="type_Request">
		<xs:sequence>
			<xs:element name="Parametri">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="TipoComunicazione" type="xs:int"/>
						<xs:element name="DataInvioRichiesta" type="xs:string"/>
						<xs:element name="CodiceOperatoreRecipient" type="xs:string"/>
						<xs:element name="CodiceOrdineRecipient" type="xs:string"/>
						<xs:element name="CodiceOLODonating" type="xs:string"/>
						<xs:element name="CodiceRisorsa1" type="xs:string"/>
						<xs:element name="CodiceServizio1" type="xs:string"/>
						<xs:element name="CodiceRisorsa2" type="xs:string"/>
						<xs:element name="CodiceServizio2" type="xs:string"/>
						<xs:element name="NomeCliente" type="xs:string"/>
						<xs:element name="CognomeClienteRagioneSociale" type="xs:string"/>
						<xs:element name="CodiceFiscalePartitaIVA" type="xs:string"/>
						<xs:element name="IdentificativoCorrelazioni" type="xs:string"/>
						<xs:element name="TotRichieste" type="xs:string"/>
						<xs:element name="Note" type="xs:string"/>
						<xs:element name="DirectoryNumber1" type="xs:string"/>
						<xs:element name="DirectoryNumber2" type="xs:string"/>
						<xs:element name="DirectoryNumber3" type="xs:string"/>
						<xs:element name="DirectoryNumber4" type="xs:string"/>
						<xs:element name="DirectoryNumber5" type="xs:string"/>
						<xs:element name="DirectoryNumber6" type="xs:string"/>
						<xs:element name="DirectoryNumber7" type="xs:string"/>
						<xs:element name="DirectoryNumber8" type="xs:string"/>
						<xs:element name="DirectoryNumber9" type="xs:string"/>
						<xs:element name="DirectoryNumber10" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="CodiceOrdineRecipient" use="required"/>
	</xs:complexType>
	
	<xs:element name="xml1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Request" type="ns1:type_Request" maxOccurs="100"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== giovannitorsello/crmcom2Server/olo2olo/testXML/n1.xml
<?xml version="1.0" encoding="utf-8"?>
<xml1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.olo.it/Request"  
      xsi:schemaLocation="http://localhost:18088/documents/xsd/xml1.xsd">
  <Request CodiceOrdineRecipient="001">
    <Parametri>
      <TipoComunicazione>123</TipoComunicazione>
      <DataInvioRichiesta>str1234</DataInvioRichiesta>
      <CodiceOperatoreRecipient>str1234</CodiceOperatoreRecipient>
      <CodiceOrdineRecipient>str1234</CodiceOrdineRecipient>
      <CodiceOLODonating>str1234</CodiceOLODonating>
      <CodiceRisorsa1>str1234</CodiceRisorsa1>
      <CodiceServizio1>str1234</CodiceServizio1>
      <CodiceRisorsa2>str1234</CodiceRisorsa2>
      <CodiceServizio2>str1234</CodiceServizio2>
      <NomeCliente>str1234</NomeCliente>
      <CognomeClienteRagioneSociale>str1234</CognomeClienteRagioneSociale>
      <CodiceFiscalePartitaIVA>str1234</CodiceFiscalePartitaIVA>
      <IdentificativoCorrelazioni>str1234</IdentificativoCorrelazioni>
      <TotRichieste>str1234</TotRichieste>
      <Note>str1234</Note>
      <DirectoryNumber1>str1234</DirectoryNumber1>
      <DirectoryNumber2>str1234</DirectoryNumber2>
      <DirectoryNumber3>str1234</DirectoryNumber3>
      <DirectoryNumber4>str1234</DirectoryNumber4>
      <DirectoryNumber5>str1234</DirectoryNumber5>
      <DirectoryNumber6>str1234</DirectoryNumber6>
      <DirectoryNumber7>str1234</DirectoryNumber7>
      <DirectoryNumber8>str1234</DirectoryNumber8>
      <DirectoryNumber9>str1234</DirectoryNumber9>
      <DirectoryNumber10>str1234</DirectoryNumber10>
    </Parametri>
  </Request>
</xml1>
